import { GetStaticProps } from "next";
import { groq } from "next-sanity";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Header from "../components/Header";
import { sanityClient, urlFor } from "../sanity";
import { RiArrowUpSFill } from "react-icons/ri";

interface Props {
  library: Library;
}

function LibraryPage({ library }: Props) {
  return (
    <div className="flex min-h-screen flex-col bg-[#040009] font-author">
      <Head>
        <title>
          {library.title} | {library.creator.name}
        </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <main>
        <img
          className="absolute top-0 h-[80vh] w-full"
          src="/gradientbg01.png"
          alt=""
        />
        <div className="relative py-10">
          <div className="flex flex-col items-center justify-center space-y-3 ">
            <div className="group space-y-2">
              <div className="gradientBorder relative rounded-3xl p-0.5">
                <div className="flex h-24 w-24 items-center justify-center rounded-3xl bg-white p-2">
                  <Image
                    src={urlFor(library.logo).url()!}
                    height="100%"
                    width="100%"
                    objectFit="contain"
                  />
                </div>
              </div>
              {/* Title */}
              <h1 className="z-10 text-center text-2xl tracking-wide text-white/90 duration-500 group-hover:scale-105 group-hover:text-white/100">
                {library.title}
              </h1>
              {/* Description */}
              <p></p>
            </div>
            {/* Author */}
            <div className="relative flex items-center justify-center space-x-5 pb-5 font-inter text-xs">
              <div className="group flex items-center space-x-2">
                <div className="relative h-7 w-7">
                  <Image
                    className="rounded-full"
                    src="/guillermo.png"
                    height={100}
                    width={100}
                  />
                </div>
                <button className="text-white/60 duration-500 group-hover:text-white/90">
                  Guillermo Rauch
                </button>
              </div>
              <div className="h-6 border-[0.5px] border-white/20"></div>
              {/* Upvotes */}
              <button className="flex items-center rounded-lg border border-white/20">
                <RiArrowUpSFill className="mx-1 text-2xl text-white/50 transition duration-300 hover:text-white/90" />
                <p className="border-l border-white/20 py-1 px-2 text-white/90">
                  150
                </p>
              </button>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default LibraryPage;

// Which pages exist
export const getStaticPaths = async () => {
  const query = groq`
        *[_type == "library"]{
             _id,
            slug {
    current
  }
}
    `;

  const libraries = await sanityClient.fetch(query);

  const paths = libraries.map((library: Library) => ({
    params: {
      slug: library.slug.current,
    },
  }));

  return {
    paths,
    fallback: "blocking",
  };
};

// Populate the data into the pages which exist and only prebuild them
export const getStaticProps: GetStaticProps<Props> = async ({ params }) => {
  const query = `*[_type == "library" && slug.current == $slug][0]{
 _id,
slug,
title,
description,
logo,
creator -> {
    name,
    slug,
    image
},
documentation
}`;

  const library = await sanityClient.fetch(query, {
    slug: params?.slug,
  });

  if (!library) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      library,
    },
    revalidate: 60, // after 60 seconds, it'll update the old cached version
  };
};
