import { GetServerSideProps } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Landing from "../components/Landing";
import Library from "../components/Library";
import LibraryTop from "../components/LibraryTop";
import { fetchLibrariesTop } from "../utils/fetchLibrariesTop";

interface Props {
  librariesTop: Library[];
}

const Home = ({ librariesTop }: Props) => {
  console.log(librariesTop);
  return (
    <div className="relative min-h-screen w-full overflow-y-hidden">
      <Head>
        <title>iconicnpm.com</title>
        <meta name="description" content="Generated by create next app" />
        /wikipedia/commons/a/a7/React-icon.svg
      </Head>
      <Header />
      <div className="my-20 lg:my-32">
        <Landing />
      </div>
      {/* Top Library */}
      <section className="relative flex-col py-20 font-author">
        <div className="space-y-2 text-center text-white">
          <h1 className="text-5xl lg:text-6xl">Explore</h1>
          <p className="text-xl text-white/40 lg:text-2xl">
            Most used libraries in today's production
          </p>
        </div>
        <div className="scrollbar-hide  flex gap-5 overflow-scroll px-5 pt-10 pb-10 lg:px-20 xl:px-40">
          {librariesTop.map((library) => (
            <LibraryTop key={library._id} library={library} />
          ))}
        </div>
      </section>
      {/* Library */}
      <section className="relative px-5 font-author lg:px-20 xl:px-40">
        <div>
          <h1 className="text-4xl text-white">Libraries</h1>
          <p className=" text-white/40 lg:text-lg">
            Explore the library and discover the incredible work of our
            community
          </p>
        </div>
        <div className="grid gap-3 pb-10 pt-5 md:grid-cols-2 ">
          <Library
            libraryLogo="/firebase.png"
            libraryName="Firebase"
            libraryDescription="Firebase is an app development platform that helps you build and grow apps and games users love. "
            libraryImage="/jamestamplin.jpeg"
            libraryAuthor="James Tamplin"
          />
          <Library
            libraryLogo="/redux.png"
            libraryName="Redux"
            libraryDescription="Redux helps you write applications that behave consistently, run in different environments (client, server, and native), and are easy to test."
            libraryImage="/danabramov.jpeg"
            libraryAuthor="Dan Abramov"
          />
          <Library
            libraryLogo="/Nextauth.png"
            libraryName="NextAuth.js"
            libraryDescription="Authentication for Next.js"
            libraryImage="/iaincollins.jpeg"
            libraryAuthor="Iain Collins"
          />
          <Library
            libraryLogo="/tailwind.png"
            libraryName="Tailwind.css"
            libraryDescription="Rapidly build modern websites without ever leaving your HTML."
            libraryImage="/adamwathan.jpeg"
            libraryAuthor="Adam Wathan"
          />
          <Library
            libraryLogo="/firebase.png"
            libraryName="Firebase"
            libraryDescription="Firebase is an app development platform that helps you build and grow apps and games users love. "
            libraryImage="/adamwathan.jpeg"
            libraryAuthor="Adam Wathan"
          />
          <Library
            libraryLogo="/redux.png"
            libraryName="Redux"
            libraryDescription="Rapidly build modern websites without ever leaving your HTML."
            libraryImage="/adamwathan.jpeg"
            libraryAuthor="Adam Wathan"
          />
          <Library
            libraryLogo="/firebase.png"
            libraryName="Firebase"
            libraryDescription="Firebase is an app development platform that helps you build and grow apps and games users love. "
            libraryImage="/adamwathan.jpeg"
            libraryAuthor="Adam Wathan"
          />
          <Library
            libraryLogo="/redux.png"
            libraryName="Redux"
            libraryDescription="Rapidly build modern websites without ever leaving your HTML."
            libraryImage="/adamwathan.jpeg"
            libraryAuthor="Adam Wathan"
          />
          <Library
            libraryLogo="/firebase.png"
            libraryName="Firebase"
            libraryDescription="Firebase is an app development platform that helps you build and grow apps and games users love. "
            libraryImage="/adamwathan.jpeg"
            libraryAuthor="Adam Wathan"
          />
          <Library
            libraryLogo="/redux.png"
            libraryName="Redux"
            libraryDescription="Rapidly build modern websites without ever leaving your HTML."
            libraryImage="/adamwathan.jpeg"
            libraryAuthor="Adam Wathan"
          />
        </div>
      </section>
      <Footer />
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps<Props> = async () => {
  const librariesTop = await fetchLibrariesTop();

  return {
    props: {
      librariesTop,
    },
  };
};
