import type { GetServerSideProps } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Landing from "../components/Landing";
import Library from "../components/Library";
import LibraryTop from "../components/LibraryTop";

interface Props {
  posts: Post[];
}

// const Login = async() => {
//   if (!user) return

//    await signInWithGoogle().then(() => {
//     console.log("signed in");

//     // Redirect to the home page
//     Router.push("/");
//   }).catch((error) => {
//     console.log(error);
//   });
// }

const Home = ({ posts }: Props) => {
  return (
    <div className="relative min-h-screen w-full overflow-y-hidden">
      <Head>
        <title>iconicnpm.com</title>
        <meta name="description" content="Generated by create next app" />
        /wikipedia/commons/a/a7/React-icon.svg
      </Head>
      <Header />
      <Landing />
      <section className="relative my-32 flex-col tracking-wide">
        <div className="space-y-5 text-center font-author text-white">
          <h1 className="text-6xl">Explore</h1>
          <p className="text-2xl text-[#c2c2c2] ">
            Most used libraries in today's production
          </p>
        </div>
        <div className="flex gap-8 overflow-scroll py-16 px-5 lg:px-20">
          <LibraryTop
            libraryLogo="/react.png"
            libraryName="React.js"
            libraryDescription="A JavaScript library for building user interfaces"
            libraryImage="/jordan.png"
            libraryAuthor="Jordan Walke"
          />
          <LibraryTop
            libraryLogo="/nextjs.png"
            libraryName="Next.js"
            libraryDescription="The React Framework for Production  The React Framework for Production"
            libraryImage="/guillermo.png"
            libraryAuthor="Guillermo Rauch"
          />
          <LibraryTop
            libraryLogo="/tailwind.png"
            libraryName="Tailwind.css"
            libraryDescription="Rapidly build modern websites without ever leaving your HTML."
            libraryImage="/adamwathan.jpeg"
            libraryAuthor="Adam Wathan"
          />
        </div>
      </section>
      <section className="pb-24">
        <h1 className="text-center font-author text-6xl  text-white">
          Libraries
        </h1>
        <div></div>
      </section>
    </div>
  );
};

export default Home;

// Server Side Rendering (SSR) - fetch data from the server - optimizes the page load time and removes loading
export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");

  const data: Post[] = await res.json();

  return {
    props: {
      posts: data,
    },
  };
};
