import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";

function Login() {
  return (
    <div className="min-h-screen flex flex-col">
      <Head>
        <title>iconicnpm.com</title>
        <meta name="description" content="Generated by create next app" />
        /wikipedia/commons/a/a7/React-icon.svg
      </Head>
      <Header />

      <main className="max-w-4xl mx-auto flex flex-col justify-center items-center flex-1">
        <Image src="/logo6.png" width={70} height={70} objectFit="contain" />
        <h2 className="text-white z-10 text-2xl">Log in to Iconic</h2>
        <div>
          <button> </button>
          <button></button>
        </div>
      </main>
    </div>
  );
}

export default Login;
