import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import { AiFillCheckCircle } from "react-icons/ai";

function pricing() {
  return (
    <div className="">
      <Head>
        <title>Pricing | Iconic</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      {/* Gradient Background */}
      <img className="absolute top-0 w-full" src="/gradientbg01.png" alt="" />
      <div className="relative px-10 text-center font-roboto text-white">
        <div className="py-10">
          <h1 className="text-3xl">Become an awesome developer</h1>
          <p>
            Learn the essential skills for modern fullstack app development
            while having tons of fun in the process.
          </p>
        </div>
        {/* Subscription */}
        <div className="flex flex-col justify-center space-y-3 md:flex-row md:items-center md:space-y-0 md:space-x-3 ">
          <div className="flex flex-col items-center space-y-1 rounded-xl border border-white/10 bg-white/10 p-5 ">
            <h1>PLAN</h1>
            <p>20/month</p>
            <div className="flex items-center justify-center space-x-2">
              <div className="rounded-xl border border-white/10 bg-white/5 px-3 py-1">
                <button>Month</button>
              </div>
              <div className="rounded-xl border border-white/10 bg-white/5 px-3 py-1">
                <button>Quarter</button>
              </div>
              <div className="rounded-xl border border-white/10 bg-white/5 px-3 py-1">
                <button>Year</button>
              </div>
            </div>
            <div className="flex flex-col items-baseline space-y-2">
              <div className="flex items-center space-x-2">
                <AiFillCheckCircle className="text-green-500" />
                <p>Unlimited access to PRO courses</p>
              </div>
              <div className="flex items-center space-x-2">
                <AiFillCheckCircle className="text-green-500" />
                <p>Quizzes with hand-picked meme prizes</p>
              </div>
              <div className="flex items-center space-x-2">
                <AiFillCheckCircle className="text-green-500" />
                <p>Invite to private Discord chat</p>
              </div>
            </div>
            <div className="pt-5">
              <button className="rounded-xl border-white/10 bg-white px-3 py-1 text-black">
                SUBSCRIBE
              </button>
            </div>
          </div>
          {/* /// */}
          <div className="flex flex-col items-center space-y-1 rounded-xl border border-white/10 bg-white/10 p-5">
            <h1>LIFETIME</h1>
            <p>100$</p>
            <div className="flex flex-col items-baseline space-y-2">
              <div className="flex items-center space-x-2">
                <AiFillCheckCircle className="text-green-500" />
                <p>Unlimited access to PRO courses</p>
              </div>
              <div className="flex items-center space-x-2">
                <AiFillCheckCircle className="text-green-500" />
                <p>Quizzes with hand-picked meme prizes</p>
              </div>
              <div className="flex items-center space-x-2">
                <AiFillCheckCircle className="text-green-500" />
                <p>Invite to private Discord chat</p>
              </div>
            </div>
            <div className="pt-5">
              <button className="rounded-xl border-white/10 bg-white px-3 py-1 text-black">
                SUBSCRIBE
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default pricing;
