import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import { FaGithub } from "react-icons/fa";
import { FcGoogle } from "react-icons/fc";
import { FiChevronRight } from "react-icons/fi";
import { useState } from "react";
import Link from "next/link";

function React() {
  return (
    <div className="flex min-h-screen flex-col bg-[#040009] font-author">
      <Head>
        <title>iconicnpm.com</title>
        <meta name="description" content="Generated by create next app" />
        /wikipedia/commons/a/a7/React-icon.svg
      </Head>
      <Header />
      <main>
        <img
          className="absolute top-0 h-[80vh] w-full"
          src="/gradientbg01.png"
          alt=""
        />
        <div className="group relative flex flex-col items-center space-y-3 px-10 font-author">
          <div className="gradientBorder rounded-3xl p-[2.5px]">
            <div className="flex h-24 w-24 items-center rounded-3xl bg-white p-2 ">
              <Image src="/react.png" height="100%" width="100%" />
            </div>
          </div>
          {/* Title */}
          <h1 className="text-center text-2xl text-white/90 duration-500 group-hover:scale-105  group-hover:text-white/100">
            React.js
          </h1>
        </div>
      </main>
    </div>
  );
}

export default React;
