import Head from "next/head";
import { FaGithub } from "react-icons/fa";
import { FcGoogle } from "react-icons/fc";
import { FiChevronRight } from "react-icons/fi";
import Header from "../components/Header";

import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import {
  useAuthState,
  useCreateUserWithEmailAndPassword,
} from "react-firebase-hooks/auth";
import { SubmitHandler, useForm } from "react-hook-form";
import { AiFillEye, AiFillEyeInvisible } from "react-icons/ai";
import { FIREBASE_ERRORS } from "../constants";
import { auth } from "../firebase";

type Inputs = {
  email: string;
  password: string;
  confirmPassword: string;
};

function Signup() {
  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm<Inputs>();
  const [user] = useAuthState(auth);
  const router = useRouter();
  const [passwordType, setPasswordType] = useState("password");
  const [createUserWithEmailAndPassword, _, loading, authError] =
    useCreateUserWithEmailAndPassword(auth);

  const togglePassword = () => {
    if (passwordType === "password") {
      setPasswordType("text");
      return;
    }
    setPasswordType("password");
  };

  const onSubmit: SubmitHandler<Inputs> = ({ email, password }) => {
    // Valid form inputs
    createUserWithEmailAndPassword(email, password);
  };

  useEffect(() => {
    if (user) router.push("/");
  }, [user]);

  return (
    <div className="flex min-h-screen flex-col bg-[#040009] font-author">
      <Head>
        <title>Signup | Iconic</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      {/* Gradient Background */}
      <img className="absolute top-0 w-full" src="/gradientbg01.png" alt="" />
      <div className="bg-gradient-to-r from-black via-[#0a0a0a] p-[1px]"></div>
      <main className="z-10 mx-auto flex w-full flex-1 flex-col items-center justify-center space-y-5  ">
        {/* Title */}
        <h1 className="text-4xl text-white">Create your account</h1>
        {/* Buttons */}
        <div className="flex w-full max-w-md space-x-4 px-5 text-white/50 sm:px-0 ">
          <div className="flex w-full justify-center rounded-md bg-white/5 p-3 transition duration-500 hover:bg-white/10">
            <FaGithub className="" />
          </div>
          <div className="flex w-full justify-center rounded-md bg-white/5 p-3 transition duration-500 hover:bg-white/10">
            <FcGoogle className="" />
          </div>
        </div>
        {/* or */}
        <small className="text-lg text-white/40">or</small>
        {/* Email */}
        <form
          className="max-w w-full max-w-md space-y-5 px-5 sm:px-0"
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="">
            <input
              type="email"
              placeholder="Email address"
              className="gradient-input relative w-full rounded-lg border-transparent bg-white/5 py-3 px-5 text-white/80 placeholder-white/40 outline-none"
              {...register("email", { required: true })}
            />
          </div>
          <div className="relative flex items-center justify-center">
            <input
              type={passwordType}
              placeholder="Password"
              autoComplete="current-password"
              className="w-full rounded-md bg-white/5 py-3 px-5 text-white/80 placeholder-white/40 outline-none "
              {...register("password", {
                required: true,
              })}
            />
            {passwordType === "password" ? (
              <AiFillEye
                className="absolute right-4 cursor-pointer text-lg text-white/20"
                onClick={togglePassword}
              />
            ) : (
              <AiFillEyeInvisible
                className="absolute right-4 cursor-pointer text-lg text-white/20"
                onClick={togglePassword}
              />
            )}
          </div>
          <div className="relative flex items-center justify-center">
            <input
              type={passwordType}
              placeholder="Confirm Password"
              autoComplete="current-password"
              className="w-full rounded-md bg-white/5 py-3 px-5 text-white/80 placeholder-white/40 outline-none"
              {...register("confirmPassword", {
                required: true,
                validate: (val: string) => {
                  if (watch("password") != val) {
                    return "Your passwords do no match";
                  }
                },
              })}
            />
            {passwordType === "password" ? (
              <AiFillEye
                className="absolute right-4 cursor-pointer text-lg text-white/20"
                onClick={togglePassword}
              />
            ) : (
              <AiFillEyeInvisible
                className="absolute right-4 cursor-pointer text-lg text-white/20"
                onClick={togglePassword}
              />
            )}
          </div>
          <p className="text-red-500">
            {errors.confirmPassword?.message ||
              FIREBASE_ERRORS[
                authError?.message as keyof typeof FIREBASE_ERRORS
              ]}
          </p>
          <button
            type="submit"
            className="flex w-full justify-center rounded-md bg-white/80 py-3 text-black/80 transition duration-500 hover:bg-white/100 hover:text-black/100"
          >
            <h1>Create account</h1>
          </button>
          <Link href="/login">
            <button className="before:gradient group relative flex w-full items-center justify-center space-x-1 rounded-md border-2 border-white/5 py-3 px-2 transition duration-500 before:rounded-md">
              <h1 className="text-white/40 transition duration-500 group-hover:text-white/100">
                I already have an account
              </h1>
              <FiChevronRight className="text-white/40 transition duration-500 group-hover:translate-x-2 group-hover:text-white/100" />
            </button>
          </Link>
        </form>
      </main>
    </div>
  );
}

export default Signup;
